cargo-features = ["edition2024"]

[package]
name = "hello"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
rig-core = { version = "0.1.0" }
tokio = { version = "1.44.1", features = ["macros", "rt-multi-thread"] }
